services:
  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always

  # app:
  #   build: .
  #   container_name: app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongo
  #   restart: always
